### ISSUE TITLE
RobotMap Usage

### ISSUE THREAD

**Issue by Silicon-E** [bubbster0506/AMESRobotics2017#2]
In several Subsystems and OI.java, there are lines of code like this:
`Victor collect = new Victor(4);`
From what I've seen, the '4' in this line refers to a motor port; this motor is assigned to port #4.
Things like this is what the RobotMap class is for, to "reduce the amount of 'magic numbers' floating around".
Assuming all of the above is correct, I would like to change the motor assignments accordingly:
`Victor collect = new Victor(RobotMap.collectPort);`

**Comment by bubbster0506** [comment]
that's an optional thing and I find it unnecessary and easier to just put the number there.

The use of having it in robot map is to make all of your static numbers in the same place rather than distributed among several different classes.  I prefer statics to just be numbers rather than a defined variable because it is easier to read the code that way.
